# Use Node image for building
FROM node:18-alpine

# Set work directory
WORKDIR /app

# Install dependencies first (for better caching)
COPY package*.json ./
COPY tsconfig.json ./

# Install dependencies
RUN npm install

# Copy project files
COPY . .

# Expose ports for the development server and WebSocket
EXPOSE 3000 35729

# Start development server with polling
ENV CHOKIDAR_USEPOLLING=true
ENV WATCHPACK_POLLING=true
ENV TSC_WATCHFILE=UseFsEventsWithFallbackDynamicPolling

# Start development server
CMD ["npm", "start"] 