version: '3.8'

services:
  # --------------------------------------------------------------------------
  # PostgreSQL Database
  # --------------------------------------------------------------------------
  db:
    image: postgres:15-alpine
    container_name: my_db
    env_file: .env
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - postgres_backups:/backups
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB}"]
      interval: 5s
      timeout: 5s
      retries: 5

  # --------------------------------------------------------------------------
  # Django Backend
  # --------------------------------------------------------------------------
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: my_django_backend
    env_file: .env
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
      - backend_static:/app/staticfiles
      - backend_media:/app/media
    depends_on:
      db:
        condition: service_healthy

  # --------------------------------------------------------------------------
  # React Frontend
  # --------------------------------------------------------------------------
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: my_react_frontend
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    depends_on:
      - backend
    environment:
      - CHOKIDAR_USEPOLLING=true  # Helps with file change detection on some systems

volumes:
  postgres_data:    # Persistent database data
    name: django_postgres_data
  postgres_backups: # For database backups
    name: django_postgres_backups
  backend_static:   # Django static files
    name: django_static_files
  backend_media:    # Django media files
    name: django_media_files 